from python:3.11

env DEBIAN_FRONTEND=noninteractive

run apt-get update && apt-get install -y \
    git

run curl -sSL https://install.python-poetry.org | python3 -

env PATH "/root/.local/bin:$PATH"

copy . /skynet

workdir /skynet

env POETRY_VIRTUALENVS_PATH /skynet/.venv

run poetry install --with=frontend -v

workdir /root/target

copy docker/entrypoint.sh /entrypoint.sh
entrypoint ["/entrypoint.sh"]

cmd ["skynet", "--help"]
