from python:3.11

env DEBIAN_FRONTEND=noninteractive

run apt-get update && apt-get install -y git

run curl -sSL https://install.python-poetry.org | python3 -

env PATH "/root/.local/bin:$PATH"

copy . /skynet

workdir /skynet

run poetry install -v
